---
title: Building your own tower
author: Michael Bach
date: '2020-04-17'
slug: building-your-own-tower
categories: ["PC"]
images: ~
---

---------------------------------------

> **TL;DR**
>
> Before starting with a new build, know what you would like to use it for. Make sure to be aware if you need certain hardware for specific tasks (e.g. NVIDIA for deep learning). Check some websites to minimize compatibility issues (e.g. [pc partpicker](https://pcpartpicker.com/) or [logical increments](https://www.logicalincrements.com/)) as well as the compatibility guidelines of your mobo. There are plenty YouTube tutorials, which are quite handy in terms of assembling guidelines (e.g. [Pauls's Hardware](https://www.youtube.com/channel/UCvWWf-LYjaujE50iYai8WgQ) or [Bitwit](https://www.youtube.com/channel/UCftcLVz-jtPXoH3cWUUDwYw)).

---------------------------------------

The call to build my own tower reached me quite late (still in my 20s though) as a tower PC wouldn't have been very handy for me. And due to budget limitations not so much fun I guess :). However, during the COVID-19 pandemic I thought it would be fun to build my own PC and run some deep learning (DL) prototypes on it. Admittedly, I bought some games too...

In this post I'm going to explain how I built my PC and add some information and resources others might find helpful when building their own PC.


## Choosing your parts

Choosing PC parts is the most time consuming but also the funniest part in my opinion. Still, it's very critical because you can make the most mistakes.

First, be sure about what you really want to do with your PC.

- Are you planning to use it for office tasks and/or gaming only?
- Would you like to run some ML models?
- How about editing some photos and videos?
- Are you going to upgrade/extend parts when you have more budget?
- Or do you just want to surf the internet and have some fancy tower with rgb lightning in your living room?

Most of these use cases involve a different budget and some special components and/or operating systems. Speaking of budget, this might be the major limitation for your build and the main reason why you simply won't be able to get the best all-in-one solution.

In my case I wanted to have a PC which can handle some deep learning model prototypes and some quality gaming fun. Luckily, most specifications are quite similar for both use cases, but could have some pitfalls as well. I'll highlight them in the upcoming sections.

### Central Processing Unit

For a decent gaming performance a CPU like the **AMD Ryzen 7 3700X** or **Intel Core i7 9700K** are sufficient. One of the later **AMD Ryzen 5** or **Intel Core i5** CPUs would do the job as well for less money. As the CPU only helps in batch scheduling and other small processes while the GPU is doing the actual model training, such a mid-range CPU should be fine for model prototyping. However, if you have GBs of data to preprocess and it fits in your budget, you might want to use the **Intel Core i9 10980XE** or the even more powerful **AMD Ryzen Threadripper 3970X**.


### CPU Cooler

Though, I decided to stick to the Wraith Prism cooler, which ships with the AMD Ryzen 7 3700X, I should have invested in a quieter one (e.g. the Dark Rock Pro 4 or the Noctua NH-D15). But in terms of cooling, it gets the job done. However, if you're thinking about using a more powerful CPU and/or more than two GPUs, you should look into an all in one water cooling system. Just make sure the cooler fits in your case and on the socket you have.


### Motherboard

The mobo is more important than I thought before. There are a few points to consider when making your decision:

- There are different sizes available and might be limited to the size of your case.
- The socket has to fit your CPU.
- You'll need multiple PCIe lanes if you want to have more than one GPU (as a GPU is quite wide you might need 4 lanes for 2 GPUs).
- The number of DIMM slots for your RAM sticks.
- The number of M2 slots for NVMe SSDs.
- The SATA slots for SSDs or HDDs.
- Any other slots you need (e.g. Thunderbolt, USB)

In case you want to upgrade your build it might come handy in the future to have some additional slots in general.

### Memory

It might not be necessary to have more than 8-16 GB of RAM for gaming or smaller data-sets. But this also depends on your usage. As stated above, if you do a lot of preprocessing more RAM would help to increase speed. Still, there are a few important things to mention here. Make sure the RAM is supported by your motherboard. If you use more than one RAM stick don't mix clock speeds. Stick to one type. And check your manual for the RAM installation, especially if you have multiple DIMM slots for your RAM.


### Storage

Storage could be quite expensive and frustrating. Therefore, evaluate what's important for you. You have the choice between **HDD**, **SSD**, and **NVMe SSD**.

The old **HDD** is a mechanical solution with a rotating magnetic disc with a brush for reading and writing bits on it. It's comparably slow, large and sensitive to damage and corruption by external influences. But they are durable and much less expensive than the other options.

**SSDs** are much faster than HDDs. They are safer as they don't have any mechanical or moving parts.

**NVMe SSDs** (Non-Volatile Memory Express) are the fastest option, but also the most expensive one. While regular SSDs have the bottleneck with their SATA 3 slots giving a max transfer of 600 Mbps, NVMe SSDs rely on PCIe with 2-3 GB/s. However, you have to check if your mobo has enough M2 slots and your storage is compatible with your mobo (check out the compatible components on the website of your mobo's manufacturer).

For me a combination of 2 NVMe SSDs and a 1 TB HDD was a good combination. I installed the OS on the SSDs (one Windows the other Linux) and use the HDD for data storage (older games, large data-sets). So I always have the option to increase speed and use the SSD if needed for training or gaming.


### Graphics Processing Unit

GPUs would need much more detail than I can give here (see [Tim Dettmers](https://timdettmers.com/2019/04/03/which-gpu-for-deep-learning/)'s blog for details). Therefore, I just briefly outline my experience.

I first thought about how many GPUs I should by. Reality hit me rather quick, though. First, it's a very expensive part and second, I wouldn't really need that many GPU power for what I plan to use my PC for. What is more, if I should find myself in the unlikely situation of running short of GPU power, there are still cloud services which scale nicely.

In terms of NVIDIA vs. AMD I choose NVIDIA simply because deep learning libraries support the NVIDIA environment better. 


### Case

The decision of which case is best highly depends on your taste. However, it was helpful for me to consider some points when making my decision:

- Mobo size: Make sure your mobo fits in your case (could be quite annoying otherwise).
- PSU fit: Although, you wouldn't have any troubles most of the time, some special or rare cases might require a certain PSU.
- Airflow vs. Quiet: Not all cases with good airflow are quiet and not all quiet cases have a good airflow. Although the difference seems to be rather small and with a few extra thoughts about cooling and cable management, neither option should negatively influence the performance. Additionally, be sure that your idea of cooling works out with your desired case (e.g. enough space for fans, radiators or the CPU cooler height).
- Convenience: 
   - Make sure to have audio jacks, USB, Thunderbolt, etc. slots available if you want them.
   - Cable management can be very different. Watch some of the videos about case assembling first to get an idea about what's important (e.g. [Pauls's Hardware](https://www.youtube.com/channel/UCvWWf-LYjaujE50iYai8WgQ) or [Bitwit](https://www.youtube.com/channel/UCftcLVz-jtPXoH3cWUUDwYw)).

Apart from that you might need some cable extensions, but you definitely need some zipping for a nice cable management.


### Power Supply Unit

Obviously, having enough watts for your build is important. To make sure to have enough power, check the specifications of your components on their manufacturer's website. Simply sum up their power consumption and add about a 10% extra (e.g. your components need 650 watts go for a PSU which supplies at least 715 watts so you could round up to 750.). As a PSU should last rather long, while other components might get replaced, it could be a good idea to invest in a more powerful PSU. So you could upgrade your PC without buying a new PSU. Finally, in case you have multiple GPUs in your build, check if your PSU has enough PCIe 8-pin or 6-pin connectors to supply them with the power they need.


### Assembling

The major advice I can give as a first time builder: Plan enough time. Although, it looks easy and fast in the tutorials, you wouldn't be able to build your PC in an hour without prior knowledge. Additionally, pay attention on how to handle your components (e.g. avoid static loading) and on cable management. Cable management could make a huge difference for your PCs performance as it might influence airflow and cause overheating components.


Apart from that, I hope this post was a bit helpful for building your own first PC. Feel free to contact me for any feedback :)


## References

[Which GPU(s) to Get for Deep Learning](https://timdettmers.com/2019/04/03/which-gpu-for-deep-learning/)

[A Full Hardware Guide to Deep Learning](https://timdettmers.com/2018/12/16/deep-learning-hardware-guide/)

[How to create your own deep learning rig](https://towardsdatascience.com/how-to-create-your-own-deep-learning-rig-a-complete-hardware-guide-2bba792b001b)


### Useful links

[pc partpicker](https://pcpartpicker.com/)

[logical increments](https://www.logicalincrements.com/)

[Pauls's Hardware](https://www.youtube.com/channel/UCvWWf-LYjaujE50iYai8WgQ)

[Bitwit](https://www.youtube.com/channel/UCftcLVz-jtPXoH3cWUUDwYw)

