---
title: Setting up your first build
author: Michael Bach
date: '2020-05-18'
slug: setting-up-your-first-build
categories: ["PC"]
images: ~
---


---------------------------------------

> **TL;DR**
>
> After building your own PC you might want to install your OS. Most will choose between Windows and a Linux distribution, but you can also have all in one with WSL 2 (Windows Subsystem for Linux) or both with a dual boot mode. I describe the setup for a dual boot mode on two physically separated SSDs. Most information is straight forward and easy to find on the Microsoft or e.g. Ubuntu website for setting up your OS. You might find some links in the post helpful, if you need additional information.

---------------------------------------

In my previous post I wrote about building my own PC. But, without an OS it's not that much fun (although it might look nice with some rgbs). Therefore, I'll focus on the OS set-up in this post.

## Operating System

For the most users the choice is between Windows or Linux. Although, it's not necessary to choose between them anymore due to [WSL 2](https://docs.microsoft.com/en-us/windows/wsl/install-win10), the Windows Subsystem for Linux. It allows you to install a full functional Linux kernel in Windows 10.

Still, when choosing my OS I decided to setup both, Windows and Linux, in dual boot mode and on two separate physical drives. The only things you need are an USB flash drive with enough storage (or CD/DVD - check if your BIOS lets you boot from the medium of your choice), another PC/notebook, and a stable internet connection.

### Windows

Starting with the Windows installation - this one is pretty straight forward. Download the Windows creation tool and ISO file for the latest Windows version from the [official Microsoft website](https://www.microsoft.com/en-us/software-download/). Then use the tool to create your installation media. Additionally, you'll need a product key for your installation. You could also finish the installation without one, but you won't be able to use all features of your installation then, therefore I'd recommend to get a product key.

As soon as you have your installation media ready open the boot menu, which you can access by pressing a key during boot (check your mobo manual to find out which key - often *F12* or *del*). Then choose your boot medium. If everything works as expected an installation screen should pop up. Within the next steps you'll need to choose your installation and type in your product key.

For certain components it might make sense to check if the necessary drivers are installed. Additionally, if you have multiple drives you should mount them. In my case the SSD including Windows was mounted - of course. But, I had to mount my HDD and format it to NTFS to use it with Windows.

That's pretty much it! Now you're good to go :)

### Linux

There are many Linux distributions available. I decided to setup the latest Ubuntu Desktop version (20.04 Focal Fossa), because I think it's great to have a large community if you run in any problems - and I like the look and feel. But, that's just a personal preference. 

You can find a detailed description of how to setup a bootable USB flash drive for your installation on the [official Ubuntu website](https://ubuntu.com/download).

Again, you have to open the boot menu and select your Ubuntu installation medium to boot from. After a few seconds you are able to choose to either install Ubuntu or to try it. If you are not sure if you want to install it, try it first.

If you decide to install it click on *Install Ubuntu*. Then select your preferred keyboard layout. At step *Updates and other Software* I decided to do the *Normal installation* instead of the *Minimal installation* to have all GUI related utilities available right after the installation. I also ticked the options in *Other options* to make sure everything works as expected.

At the *Installation type* section, I choose *Something else* as I wanted to have my own customized partition scheme on a separate SSD. To create a partition table select the device for your installation. Then click *New Partition Table...*. Use a forward slash (/) for your mount point, then you should be good to go. You might want to add a swap partition in case you run out of RAM with data intensive applications (see https://www.makeuseof.com/tag/swap-partition/ for more details). I did not create any other partitions.

Finally, choose your timezone and user credentials and you're good to go :).

If you need some screenshots or more in depth information, I found this post at [Linux Techi](https://www.linuxtechi.com/ubuntu-20-04-lts-installation-steps-screenshots/) very informative.

What I've been struggling with was my additional HDD. During the Windows installation I formatted it as NTFS and mounted it in Windows but forgot to mount it permanently in Linux. When I used the HDD within Linux it was mounted without any problems, but it was mounted only when I explicitly used it. Therefore, paths to the folders changed slightly (e.g. my-storage/folder -> my-storage1/folder) as the drive was newly mounted all the time. So I ended up with multiple paths in the end...

Luckily the solution was fairly simple:

* Go to Applications/Utilities/Disks
* Highlight your drive
* Click the little gear wheels and click *Edit Mount Options*
* Make sure that the option *Mount at system startup* is checked

Alternatively you could modify your ftab file directly to mount your drive at system startup.

I hope this post was informative. Feel free to contact me for any feedback :)




